### PR TITLE
Fix travis and ignore some build artifacts

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by untitaker** [comment]
@RonnyPfannschmidt ready for review, the testcases fail because setuptools_scm is somehow broken on Py2 and nightly.

**Comment by untitaker** [comment]
Failures in nightly are probably due to https://github.com/pytest-dev/pytest/issues/744

**Comment by RonnyPfannschmidt** [comment]
once you rebase i'll merge on the ui
i hope i can do a release this evening

**Comment by untitaker** [comment]
...that was messy. Why did you merge https://github.com/pypa/setuptools_scm/commit/257fd6d1a741ab77c8b1dc5742f8be195bbad957 :(

**Pull request merged**
